### ISSUE TITLE
Skill section View

### ISSUE THREAD

**Issue by Raaghul29** [mack-1999/Makarand-Nikam-Portfolio#1]
seems like your skills section is merged with the experience section and found an issue with the responsive design or may be a css issue.
![image](https://user-images.githubusercontent.com/35929738/89104114-6d939d80-d434-11ea-9ed0-7c127b5c8fbb.png)

**Comment by mack-1999** [comment]
Thanks for informing issue I will check it and solve it as early as possible.

**Comment by mack-1999** [comment]
I have check from my side there is not any issues I have tested in 3 different web browser but I haven't seen that problem.
